asciidoc:
  attributes:
    idprefix: "@"
    idseparator: '-'
    page-copyright-ownership: "Barcelona City Council, Decidim Free Software Association and the authors of the text@"
    page-license: "Creative Commons Attribution-ShareAlike 4.0 International (CC-BY-SA-4.0)@"
    page-license-alternative: "GNU Free Documentation (GFDL-1.3-or-later)@"
    page-playbook-lang: en
    sectanchors: ''
    xrefstyle: "short@"
content:
  sources:
    - branches:
        - master
      start_path: en
      url: https://github.com/decidim/docs-base
    - branches:
        - master
      start_path: en
      url: https://github.com/decidim/docs-publications
    - branches:
        - master
      start_path: en
      url: https://github.com/gmarpons/docs-test
    - branches:
        - v1.0
      start_path: en
      url: https://github.com/gmarpons/docs-test
    - branches:
        - revamp2020
      start_path: en
      url: https://github.com/decidim/docs-features
output:
  destinations: []
  dir: build/site/en
runtime:
  cache_dir: "./.cache/antora"
  fetch: true
site:
  start_page: decidim:ROOT:index.adoc
  title: Decidim Docs
  url: https://docs.decidim.org/en
ui:
  bundle:
    snapshot: true
    url: "https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable"
  supplemental_files: "./supplemental_ui"
