[build]
publish = "public"
ignore = "false"

[build.environment]
CI = "true"
NODE_VERSION = "12"
# WARNING netlify-build ignores NPM_FLAGS when installing plugins, so use low-level NPM_CONFIG_ flag instead
#NPM_FLAGS = "--no-optional"
NPM_CONFIG_OPTIONAL = "false"
ANTORA_CACHE_DIR = "node_modules/.cache/antora"

# NOTE the --fetch flag is needed on both calls to update both the content and UI bundle (since the xref validator doesn't fetch the UI)

[context.production]
command = """\
DOCSEARCH_ENABLED=true DOCSEARCH_ENGINE=lunr NODE_PATH="$(npm -g root)" node_modules/.bin/antora --fetch --generator antora-site-generator-lunr --html-url-extension-style=indexify --redirect-facility=netlify --to-dir=public/ca ../antora-playbook.remote.ca.yml &&\
sed -r 's;^/([[:graph:]]*)[[:space:]]+/(.*);/ca/\\1 /ca/\\2;' public/ca/_redirects >> public/_redirects &&\
DOCSEARCH_ENABLED=true DOCSEARCH_ENGINE=lunr NODE_PATH="$(npm -g root)" node_modules/.bin/antora --fetch --generator antora-site-generator-lunr --html-url-extension-style=indexify --redirect-facility=netlify --to-dir=public/en ../antora-playbook.remote.en.yml &&\
sed -r 's;^/([[:graph:]]*)[[:space:]]+/(.*);/en/\\1 /en/\\2;' public/en/_redirects >> public/_redirects &&\
DOCSEARCH_ENABLED=true DOCSEARCH_ENGINE=lunr NODE_PATH="$(npm -g root)" node_modules/.bin/antora --fetch --generator antora-site-generator-lunr --html-url-extension-style=indexify --redirect-facility=netlify --to-dir=public/es ../antora-playbook.remote.es.yml &&\
sed -r 's;^/([[:graph:]]*)[[:space:]]+/(.*);/es/\\1 /es/\\2;' public/es/_redirects >> public/_redirects &&\
echo "cat public/_redirects:" &&\
cat public/_redirects\
"""

[context.deploy-preview]
command = """\
DOCSEARCH_ENABLED=true DOCSEARCH_ENGINE=lunr NODE_PATH="$(npm -g root)" node_modules/.bin/antora --fetch --generator antora-site-generator-lunr --html-url-extension-style=indexify --redirect-facility=netlify --to-dir=public/ca --url $DEPLOY_PRIME_URL ../antora-playbook.remote.ca.yml &&\
sed -r 's;^/([[:graph:]]*)[[:space:]]+/(.*);/ca/\\1 /ca/\\2;' public/ca/_redirects >> public/_redirects &&\
DOCSEARCH_ENABLED=true DOCSEARCH_ENGINE=lunr NODE_PATH="$(npm -g root)" node_modules/.bin/antora --fetch --generator antora-site-generator-lunr --html-url-extension-style=indexify --redirect-facility=netlify --to-dir=public/en --url $DEPLOY_PRIME_URL ../antora-playbook.remote.en.yml &&\
sed -r 's;^/([[:graph:]]*)[[:space:]]+/(.*);/en/\\1 /en/\\2;' public/en/_redirects >> public/_redirects &&\
DOCSEARCH_ENABLED=true DOCSEARCH_ENGINE=lunr NODE_PATH="$(npm -g root)" node_modules/.bin/antora --fetch --generator antora-site-generator-lunr --html-url-extension-style=indexify --redirect-facility=netlify --to-dir=public/es --url $DEPLOY_PRIME_URL ../antora-playbook.remote.es.yml &&\
sed -r 's;^/([[:graph:]]*)[[:space:]]+/(.*);/es/\\1 /es/\\2;' public/es/_redirects >> public/_redirects &&\
echo "cat public/_redirects:" &&\
cat public/_redirects\
"""

[[plugins]]
package = "netlify-plugin-checklinks"

[plugins.inputs]
entryPoints = [
  "**/index.html"
]
recursive = true
pretty = true
skipPatterns = [
  "404.html"
]
todoPatterns = []
checkExternal = false
followSourceMaps = false

[[headers]]
for = "/_/font/*"
  [headers.values]
  Cache-Control = "public,max-age=604800"

# ...or define headers in _headers file to allow use of netlify command (not currently used)
# /_/font/*
#  Cache-Control: public,max-age=604800

# NOTE the following redirects get appended to the redirects defined in the _redirects file

[[redirects]]
from = "/*"
to = "/en/:splat"
status = 301
force = false

# [[redirects]]
# from = "/antora/1.1/*"
# to = "/antora/latest/:splat"
# status = 301
# force = true

# [[redirects]]
# from = "/antora/latest/*"
# to = "/antora/2.3/:splat"
# status = 302
# force = true
